In [9]:
# Question 1: Arrays.

import numpy

def arrays(arr):
    my_arr = numpy.array(arr, float)
    return my_arr[::-1]

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 7 -6 85 7 3 9 -7
[-7.  9.  3.  7. 85. -6.  7.  1.]


In [5]:
# Question 2: Shape and Reshape.

import numpy as np

list1 = list(map(int, input().split()))
arr = np.array(list1)
print(arr.reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
# Question 3 : Transpose and Flatten

import numpy as np

n, m = map(int, input().split())
arr = []
for i in range(n):
    x = []
    x = list(map(int, input().split()))
    arr.append(x)
    
my_arr = np.array(arr)
print(my_arr.T)
print(my_arr.flatten())

2 4
1 2 3 4
5 6 7 8
[[1 5]
 [2 6]
 [3 7]
 [4 8]]
[1 2 3 4 5 6 7 8]


In [33]:
# Question 4 : Concatenate.

import numpy as np

n, m, p = map(int, input().split())

list_N, list_M = [], []

for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    list_N.append(x)
array_N = np.array(list_N)

for j in range(0, m):
    x = []
    x = list(map(int, input().split()))
    list_M.append(x)
array_M = np.array(list_M)

print(np.concatenate((array_N, array_M), axis = 0))

2 3 2
1 2
4 5
7 8
9 6
3 5
[[1 2]
 [4 5]
 [7 8]
 [9 6]
 [3 5]]


In [51]:
# Question 5 : Zeros and Ones

import numpy as np

x = tuple(map(int, input().split()))
print(np.zeros(x, dtype = np.int))
print(np.ones(x, dtype = np.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [4]:
# Question 6 : Eye and Identity.

import numpy as np

n, m = map(int, input().split())
np.set_printoptions(sign=' ')
print(np.eye(n, m, 0))

4 4
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [9]:
# Question 7 : Array Mathematics.

import numpy as np

n, m = map(int, input().split())

arr1, arr2 = [], []
for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    arr1.append(x)
ar1 = np.array(arr1)

for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    arr2.append(x)
ar2 = np.array(arr2)

print(ar1+ar2)
print(ar1-ar2)
print(ar1*ar2)
print(ar1//ar2)
print(ar1%ar2)
print(ar1**ar2)

1 3
1 2 3
4 5 6
[[5 7 9]]
[[-3 -3 -3]]
[[ 4 10 18]]
[[0 0 0]]
[[1 2 3]]
[[  1  32 729]]


In [13]:
# Question 8 : Floor, Ceil and Rint

import numpy as np

np.set_printoptions(legacy = '1.13')
arr1 = np.array(list(map(float, input().split())))

print(np.floor(arr1))
print(np.ceil(arr1))
print(np.rint(arr1))

1.0 1.1 1.2 1.3 1.4 1.5 1.6 2.8 2.7 2
[ 1.  1.  1.  1.  1.  1.  1.  2.  2.  2.]
[ 1.  2.  2.  2.  2.  2.  2.  3.  3.  2.]
[ 1.  1.  1.  1.  1.  2.  2.  3.  3.  2.]


In [17]:
# Question 9 : Sum and Prod

import numpy as np

n, m = map(int, input().split())
list1 = []

for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    list1.append(x)

arr1 = np.array(list1)
sum_along_0_axis = np.sum(arr1, axis = 0)
print(np.prod(sum_along_0_axis))

2 2
2 3
3 7
50


In [20]:
# Question 10 : Min and Max

import numpy as np

n, m = map(int, input().split())
list1 = []
for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    list1.append(x)
arr = np.array(list1)
min_arr = arr.min(axis = 1)
print(min_arr.max())

3 3
1 2 3
4 5 6
7 8 9
7


In [30]:
# Question 11 : Mean, Var and Std.

import numpy as np

n, m = map(int, input().split())

list1 = []

for i in range(0, n):
    x = []
    x = list(map(int, input().split()))
    list1.append(x)
 
arr = np.array(list1)
print(np.mean(arr, axis = 1))
print(np.var(arr, axis = 0))
print("{:.11f}".format(np.std(arr, axis = None)))

2 3
1 2 3
1 4 1
[ 2.  2.]
[ 0.  1.  1.]
1.15470053838


In [32]:
# Question 12 : Dot and Cross. 

import numpy as np

n = int(input())
a = []
for i in range(0, n):
    x = list(map(int, input().split()))
    a.append(x)
A = np.array(a)

b = []
for i in range(0, n):
    x = list(map(int, input().split()))
    b.append(x)
B = np.array(b)

print(np.dot(A, B))

2
1 2
2 3
4 5
2 1
[[ 8  7]
 [14 13]]


In [33]:
# Question 13 : Inner and Outer

import numpy as np

A = np.array(list(map(int, input().split())))
B = np.array(list(map(int, input().split())))
print(np.inner(A, B))
print(np.outer(A, B))

2 3
4 5
23
[[ 8 10]
 [12 15]]


In [35]:
# Question 14 : Polynomials 

import numpy as np
P = np.array(list(map(float, input().split())))
x = int(input())
print(np.polyval(P, x))

1.1 2 3
0
3.0


In [43]:
# Question 15 : Linear Algebra

import numpy as np

n = int(input())
a = []
for i in range(0, n):
    x = list(map(float, input().split()))
    a.append(x)
    
arr = np.array(a)
x = "{:.2f}".format(np.linalg.det(arr))

if float(x) == round(float(x)):
    print(float(x))
else:
    print(x)

3
1 2 3
4 5 6
1 2 1
6.0
